Fixing _clebold function name

diff --git a/clerc b/clerc
--- a/clerc
+++ b/clerc
@@ -149,7 +149,7 @@ EOT
 }
 
 # boldprint
-_clepbold () { printf "$_CL$*$_CN\n";}
+_clebold () { printf "$_CL$*$_CN\n";}
 
 # simple question
 _cleask () (
@@ -674,7 +674,7 @@ done
 if [ "$CLE_MOTD" ]; then
 	[ -f /etc/motd ] && cat /etc/motd
 	printf "\n$CLE_MOTD"
-	_clepbold "\n CLE $CLE_VER\n"
+	_clebold "\n CLE $CLE_VER\n"
 	unset CLE_MOTD
 fi
 
@@ -811,7 +811,7 @@ cle () {
 		rev)	cp $CLE_CF-bk $CLE_CF;;
 		"")
 			if [ -f $CLE_CF ]; then
-				_clepbold $_CU$CLE_CF:
+				_clebold $_CU$CLE_CF:
 				cat $CLE_CF
 			else
 				echo Default/Inherited configuration
@@ -827,7 +827,7 @@ cle () {
 		unset CLE_1
 		I='# Command Live Environment'
 		S=$HOME/.${SHELL##*/}rc
-		grep -A1 "$I" $S && _clepbold CLE is already hooked in $S && return 1
+		grep -A1 "$I" $S && _clebold CLE is already hooked in $S && return 1
 		_cleask "Do you want to add CLE to $S?" || return
 		echo -e "\n$I\n[ -f $CLE_RC ] && . $CLE_RC\n" | tee -a $S
 		cle reload;;
@@ -857,7 +857,7 @@ cle () {
 		N=cle-mod
 		P=$CLE_D/$N
 		curl -k $CLE_SRC/modules/$N >$P
-		grep -q "# .* $N:" $P || { _clepbold Module download failed; rm -f $P; return 1;}
+		grep -q "# .* $N:" $P || { _clebold Module download failed; rm -f $P; return 1;}
 		cle mod "$@";;
 	env)	## `cle env`               - inspect variables
 		_clevdump 'CLE.*'|awk -F= "{printf \"$_CL%-12s$_CN%s\n\",\$1,\$2}";;
