Big cleanup... - search for unnecessary stuff (spaces, quotes where they weren't needed) code radability should not be affected much, I hope - some renaming:     CLE_DIR -> CLE_D     CLE_VERSION -> CLE_VER - comments and information texts edit
Color table initialization reprogrammed with loop
Small fix in 'cle help' - it wasn't able to find help in modules

Wth all this I saved approximately 1.2kB of the code :-) Will be checking if
all works like expected before adding new features!

diff --git a/clerc b/clerc
--- a/clerc
+++ b/clerc
@@ -4,7 +4,7 @@
 #* authors: Michael Arbet (marbet@redhat.com)
 #*          Jakub Arbet (arbetjakub@gmail.com)
 #* home:    https://github.com/micharbet/CLE
-#* version: 2017-05-18 (HAlpha)
+#* version: 2017-05-21 (HAlpha)
 #* license: GNU GPL v2
 #* Copyright (C) 2016-2017 by Michael Arbet 
 #
@@ -14,13 +14,12 @@
 # of the License, or (at your option) any later version.
 #
 # Command line tweaks:
-# - colorized prompt incl hihglighted exit code
+# - colorful prompt incl hihglighted exit code
 # - builtin aliases and functions
 # - history tweaks (timestamps etc)
-# - history personalized for multi-admin environment
 #
-# Execute this file within your shell session once and integrate
-# into your profile with 'cle deploy' command
+# Execute this file within your shell session
+# and integrate into your profile:
 # 
 #	$ . clerc
 #	$ cle deploy
@@ -29,12 +28,12 @@
 #   started without installation
 # - try suu/sudd (su/sudo wrappers) with same effect
 # - alter settings using 'cle' command
-# - built-in self documenting feature ('cle help')
 # - store and manage your aliases with 'aa' function
 # - use 'hh' function to ease history management
-# - self update from GIT source
+# - built-in self documenting feature 'cle help'
+# - update from GIT source
 
-# check running in interactive session and if not, skip all the tweaks
+# check running in interactive session otherwise skip all the tweaks
 # required for scp compattibility
 if [ -t 0 -a -z "$CLE_EXE" ]; then
 
@@ -54,9 +53,9 @@ fi
 
 # where in the deep space is CLE growing
 CLE_SRC=https://raw.githubusercontent.com/micharbet/CLE/master
-CLE_VERSION=`sed -n 's/^#\* version: //p' $CLE_RC`
+CLE_VER=`sed -n 's/^#\* version: //p' $CLE_RC`
 
-# execute script and log its filename into CLE_EXE to keep track
+# execute script and log its filename into CLE_EXE
 # also ensure the script will be executed only once
 _clexe () {
 	if [ -f "$1" ]; then
@@ -72,37 +71,37 @@ case $CLE_RC in
 *.clerc-remote-*) # remote session
 	_clexe /etc/profile
 	_clexe $HOME/.bashrc
-	[ -w $HOME ] && CLE_DR=$HOME || CLE_DR=`dirname $CLE_RC` ;;
+	[ -w $HOME ] && CLE_DT=$HOME || CLE_DT=`dirname $CLE_RC`;;
 */clerc*) # first run from commandline
 	[ -z "$CLE_DK" ] && CLE_FIRST=1
-	CLE_DR=$HOME ;;
+	CLE_DT=$HOME;;
 *)	# locally deployed
-	CLE_DR=$HOME
+	CLE_DT=$HOME
 esac
-CLE_DIR=${CLE_DIR:-$CLE_DR}
+CLE_D=${CLE_D:-$CLE_DT}
 
-CLE_CF=${CLE_CF:-$CLE_DIR/.clecf-$CLE_USER}
+CLE_CF=${CLE_CF:-$CLE_D/.clecf-$CLE_USER}
 CLE_RCU=$CLE_DRC/.cleusr-$CLE_USER
 
-# tweaked hostname, can be altered in .clerc-local or .cleusr-$CLE_USER
-CLE_THN=`hostname |sed 's;\.\w\+\.\w\+$;;'` # remove domain, leave subdomains
+# tweaked hostname: remove domain, leave subdomains
+CLE_THN=`hostname |sed 's;\.\w\+\.\w\+$;;'`
 CLE_IP=`echo -n $SSH_CONNECTION | cut -d' ' -f3`
 
-# color table initializattion
+# color table
 CT_N=`tput sgr0`
 CT_L=`tput bold`
 CT_U=`tput smul`; CT_UE=`tput rmul`
 CT_D=`tput dim`
 CT_RV=`tput rev`
-CT=`tput setaf 0`; CT_k=$CT_N$CT; CT_K=$CT_L$CT
-CT=`tput setaf 1`; CT_r=$CT_N$CT; CT_R=$CT_L$CT
-CT=`tput setaf 2`; CT_g=$CT_N$CT; CT_G=$CT_L$CT
-CT=`tput setaf 3`; CT_y=$CT_N$CT; CT_Y=$CT_L$CT
-CT=`tput setaf 4`; CT_b=$CT_N$CT; CT_B=$CT_L$CT
-CT=`tput setaf 5`; CT_m=$CT_N$CT; CT_M=$CT_L$CT
-CT=`tput setaf 6`; CT_c=$CT_N$CT; CT_C=$CT_L$CT
-CT=`tput setaf 7`; CT_w=$CT_N$CT; CT_W=$CT_L$CT
+CI=0; for CN in k r g y b m c w; do
+        CL=`tput setaf $CI`
+        declare CT_$CN=$CT_N$CL #dim
+        declare CT_${CN^}=$CT_L$CL #bold
+        (( CI += 1 ))
+done
+unset CI CN CL
 CT_E=`tput setab 1; tput setaf 7` # err highlight
+
 
 #
 # Internal helper functions
@@ -115,7 +114,7 @@ printb () { printf "$CT_w$*$CT_N\n"; }
 ask () {
 	read -p "$CT_L$* (y/N) $CT_N" -n 1 -s
 	echo ${REPLY:=n}
-	[ "$REPLY" == "y" ]
+	[ "$REPLY" = "y" ]
 }
 
 # banner
@@ -133,14 +132,14 @@ EOT
 # default window title
 _defwt () {
 	CLE_WT=''
-	[[ $TERM =~ 'linux' ]] && return # no tits on console
+	[[ $TERM =~ linux ]] && return # no tits on console
 	[[ $CLE_RC =~ remote ]] && CLE_WT="$CLE_USER -> "
-	CLE_WT="$CLE_WT$USER@$CLE_THN:"
+	CLE_WT=$CLE_WT$USER@$CLE_THN:
 }
 
 # default config
 _defcf () {
-	CLE_PCOLOR='marley'
+	CLE_PCOLOR=marley
 	CLE_P0='%e \A'
 	CLE_P1='\u'
 	CLE_P2='%h'
@@ -149,8 +148,8 @@ _defcf () {
 
 # save configuration
 _savecf () {
-	echo "# $CLE_USER $CLE_VERSION"
-	echo CLE_PCOLOR=\'$CLE_PCOLOR\'
+	echo "# $CLE_USER $CLE_VER"
+	echo CLE_PCOLOR=$CLE_PCOLOR
 	echo CLE_P0=\'$CLE_P0\'
 	echo CLE_P1=\'$CLE_P1\'
 	echo CLE_P2=\'$CLE_P2\'
@@ -160,7 +159,7 @@ _savecf () {
 # prompt enhancements
 _pesc () {
 	local PP=">" # I hate $ in prompt
-	[ $UID == 0 ] && PP="#"
+	[ $UID = 0 ] && PP="#"
 	echo $*|sed \
 	 -e "s/%i/$CLE_IP/" \
 	 -e "s/%h/$CLE_THN/" \
@@ -202,8 +201,8 @@ _setp () {
 	*)	# print help - whoa! self documented function :)
 		echo "Unknown color '$CLE_PCOLOR' Select one of predefined:"
 		declare -f _setp|sed -n -e 's/\ *\(\<[a-zA-Z |]*\)).*/ \1 /p' 
-		echo "Or create your own 3-letter style using: rgbcmykw / RGBCMYKW"
-		echo " e.g. 'cle color rgB'"
+		echo Or create your own 3-letter style using: rgbcmykw / RGBCMYKW
+		echo e.g. cle color rgB
 		return 2 
 	esac
 	# prepare prompt strings
@@ -218,7 +217,7 @@ _clepmt () {
 	_E=$? # save return code
 	local EE
 	# highlight error code only in P0
-	[ $_E -eq 0 ] && EE="[0]" || EE="\[$CT_E\][$_E]\[$CT_N$CT_K\]"
+	[ $_E -eq 0 ] && EE=[0] || EE="\[$CT_E\][$_E]\[$CT_N$CT_K\]"
 	# final prompt composition
 	PS1="\[$CT_K\]${_PS0/'$_E'/$EE} $_PS1 \[$CT_N\]"
 	# window title
@@ -243,12 +242,12 @@ mdfilter () {
 ## ------------------------------
 _defalias () {
 	## ls commands aliases: l ll la lt llr l. lld
-	if [[ "$OSTYPE" =~ "linux" ]]; then
+	if [[ "$OSTYPE" =~ linux ]]; then
                 alias ls='ls --color=auto'
-        elif [[ "$OSTYPE" =~ "darwin" ]]; then
+        elif [[ "$OSTYPE" =~ darwin ]]; then
                 export CLICOLOR=1
-                export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
-        elif [[ "$OSTYPE" =~ "freebsd" ]]; then
+                export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
+        elif [[ "$OSTYPE" =~ freebsd ]]; then
                 alias ls='ls -G'
 	else
 		alias ls='ls -F' # at least some file type indication
@@ -281,7 +280,7 @@ _defalias () {
 ##
 ## Alias management
 ## ----------------
-CLE_ALIASES=$CLE_DIR/.aliases-$CLE_USER # personalized aliases
+CLE_ALIASES=$CLE_D/.aliases-$CLE_USER # personalized aliases
 _clexe $CLE_ALIASES
 _defalias
 
@@ -289,17 +288,17 @@ aa () {
 	local ABAK=$CLE_ALIASES.back
 	case "$1" in
 	"")	## aa         -- show aliases
-		alias ;;
+		alias;;
 	s)	## aa s       -- save your set of aliases
 		alias
-		ask "Save aliases?" || return
+		ask Save aliases? || return
 		cp $CLE_ALIASES $ABAK
 		alias >$CLE_ALIASES
 		printb Saved to file: $CLE_ALIASES
-		printb Backup in: $ABAK ;;
+		printb Backup in: $ABAK;;
 	l)	## aa l       -- (re)load your set of aliases
 		unalias -a
-		. $CLE_ALIASES ;;
+		. $CLE_ALIASES;;
 	ed)	## aa ed      -- edit and reload your aliases
 		local TALIAS=$CLE_ALIASES.edit
 		alias >$ABAK
@@ -307,9 +306,9 @@ aa () {
 		vi $TALIAS
 		mv $TALIAS $CLE_ALIASES
 		aa l
-		printb Backup in: $ABAK ;;
+		printb Backup in: $ABAK;;
 	*)	
-		echo " unimplemented: aa $1 $2"
+		echo unimplemented: aa $1 $2
 		cle help aa
 	esac
 }
@@ -320,12 +319,12 @@ aa () {
 hh () {
 	case $1 in
 	"")	## hh         -- just print history
-		history ;;
+		history;;
 	shon)	## hh shon    -- turn on sharing history between terminals
-		CLE_HSH=1 ;;
+		CLE_HSH=1;;
 	[0-9]|[0-9][0-9]|[0-9][0-9][0-9])
 		## hh number  -- print last N entries
-		history $1 ;;
+		history $1;;
 	*)	## hh string  -- search in history
 		history | grep -i $1
 	esac
@@ -383,7 +382,7 @@ export EDITOR=vi
 export PAGER="less -s"
 PROMPT_DIRTRIM=2
 shopt -s checkwinsize
-HISTFILE=$CLE_DIR/.history-$CLE_USER
+HISTFILE=$CLE_D/.history-$CLE_USER
 # history file must not be empty!
 [ -f $HISTFILE ] || { cp $HOME/.bash_history $HISTFILE 2>/dev/null || echo ls >$HISTFILE; }
 HISTCONTROL=ignoredups
@@ -392,7 +391,7 @@ HISTTIMEFORMAT="%d%b %H:%M:%S  "
 # load config and custom tweaks
 _clexe $CLE_CF
 [ -n "$CLE_VERB" ] && cat $CLE_CF
-_clexe $CLE_DIR/.clerc-local
+_clexe $CLE_D/.clerc-local
 _clexe $CLE_RCU
 
 # indicate first run, show banner, create default conf
@@ -405,7 +404,7 @@ $CT_L    cle deploy$CT_N
 EOT
 
 # load modules from .cle folder
-for MD in $CLE_DIR/.cle/mod-*; do
+for MD in $CLE_D/.cle/mod-*; do
 	_clexe $MD
 done
 unset MD
@@ -421,101 +420,99 @@ _setp
 ## ----------------------
 cle () {
 	local CMD=$1; shift
+	# find & run enhancement _cle_* function
 	if declare -f _cle_$CMD >/dev/null; then
-		# run any _cle_* function
-		# those can be defined in modules and user tweaks
 		_cle_$CMD $*
 		return $?
 	fi
-	case "${CMD}" in
+	case "$CMD" in
 	color)	## cle color COLOR    -- set prompt color
 		local CPC=$CLE_PCOLOR
 		CLE_PCOLOR=$1
-		_setp || CLE_PCOLOR=$CPC ;;
+		_setp || CLE_PCOLOR=$CPC;;
 	p0)	## cle p0-p3 [string] -- define prompt part 0-3
 		CLE_P0="${*:-%e \A}"
-		_setp ;;
+		_setp;;
 	p1)
 		CLE_P1="${*:-\\u}"
-		_setp ;;
+		_setp;;
 	p2)
 		CLE_P2="${*:-%h}"
-		_setp ;;
+		_setp;;
 	p3)
 		CLE_P3="${*:-\\w %>}"
-		_setp ;;
+		_setp;;
 	time)	## cle time [off]     -- toggle server time in prompt
-		[ "$1" == "off" ] && CLE_P0='%e'
+		[ "$1" = off ] && CLE_P0=%e
 		[ -z "$1" ] && CLE_P0='%e \A'
-		_setp ;;
+		_setp;;
 	title)	## cle title [off]    -- toggle window title
-		[ "$1" == "off" ] && CLE_WT=''
+		[ "$1" = off ] && CLE_WT=''
 		[ -z "$1" ] && _defwt 
 		;;
 	deploy)
 		## cle deploy         -- hook CLE into user's profile
 		local CLID='# Command Live Environment'
 		local BRC=$HOME/.bashrc
-		cp $CLE_RC $CLE_DIR/.clerc
-		grep -q "$CLID" $BRC 
-		if [ $? != 0 ]; then
-			printb "CLE is to be integrated to your login script."
-			ask " Are you sure?" || return
-			echo -e >>$BRC \\n$CLID
-			echo -e >>$BRC "[ -f $CLE_DIR/.clerc ] && . $CLE_DIR/.clerc\n"
-			printb '\n ...lines added to your .bashrc :'
-			tail -2 $BRC
-		else
-			printb "CLE is already hooked into .bashrc :"
+		cp $CLE_RC $CLE_D/.clerc
+		if grep -q "$CLID" $BRC; then
+			printb CLE is already hooked into .bashrc :
 			command grep -A2 "$CLID" $BRC
-		fi ;;
+		else
+			printb CLE is to be integrated to your login script.
+			ask Are you sure? || return
+			echo -e >>$BRC \\n$CLID
+			echo -e >>$BRC "[ -f $CLE_D/.clerc ] && . $CLE_D/.clerc\n"
+			printb Lines added to your .bashrc :
+			tail -3 $BRC
+		fi;;
 	update) ## cle update         -- install fresh version of CLE
 		if [[ $CLE_RC =~ remote ]]; then
 			printb CLE in remote session, update is pointless.
 			return 1
 		fi
-		local NCLE=$CLE_DIR/clerc-new
+		local NCLE=$CLE_D/clerc-new
 		curl -k $CLE_SRC/clerc >$NCLE
-		printb "New CLE here: $NCLE"
-		echo "current: $CLE_VERSION"
+		printb New CLE here: $NCLE
+		echo current: $CLE_VER
 		echo "new:     `sed -n 's/^#\* version: //p' $NCLE`"
 		local SUM1=`md5sum $CLE_RC| cut -d' ' -f1`
 		local SUM2=`md5sum $NCLE| cut -d' ' -f1`
-		[ $SUM1 == $SUM2 ] && { echo No difference; return 1; }
-		ask "Do you want to see diff?" && diff $CLE_RC $NCLE
-		ask "Do you want to install new version?" || return
-		cp $CLE_RC $CLE_DIR/clerc-back
+		[ $SUM1 = $SUM2 ] && { echo No difference; return 1; }
+		ask Do you want to see diff? && diff $CLE_RC $NCLE
+		ask Do you want to install new version? || return
+		cp $CLE_RC $CLE_D/clerc-back
 		mv $NCLE $CLE_RC
 		cle reload
-		printb "New CLE has been installed, previous version saved here: $CLE_DIR/clerc-back" ;;
+		printb New CLE activated, previous saved here: $CLE_D/clerc-back;;
 	reload) ## cle reload         -- reload CLE
 		unset CLE_EXE
 		printb Reloading CLE from $CLE_RC
 		. $CLE_RC
-		echo CLE $CLE_VERSION ;;
+		echo CLE $CLE_VER;;
 	mod)	## cle mod            -- cle module management
-		# this is just a fallback for initialize modularity
+		# this is just a fallback to initialize modularity
 		# downloaded mod-mod overrides this code 
-		ask "Activate CLE modules?" || return
-		local MM=$CLE_DIR/.cle/mod-mod
-		mkdir $CLE_DIR/.cle
+		ask Activate CLE modules? || return
+		local MM=$CLE_D/.cle/mod-mod
+		mkdir $CLE_D/.cle
 		curl -k $CLE_SRC/dotcle/mod-mod >$MM
 		grep -q '# mod-mod:' $MM || { printb module download failed; rm -f $MM; return 1; }
 		_clexe $MM
 		cle mod avail
 		;;
 	env)	## cle env            -- print CLE_* variables
-		set | grep ^CLE_.*= ;;
+		set | grep ^CLE_.*=;;
 	cf)	## cle cf             -- show configuration
 		printb Config: $CLE_CF
-		cat $CLE_CF ;;
+		cat $CLE_CF;;
 	reset)	## cle reset          -- reset configuration
 		rm -f $CLE_CF
-		cle reload ;;
+		cle reload;;
 	readme) ## cle readme         -- download and show README file
-		curl -k $CLE_SRC/README.md | mdfilter |less -r ;;
+		curl -k $CLE_SRC/README.md | mdfilter |less -r;;
 	man)	## cle man            -- download and show HOWTO file
-		curl -k $CLE_SRC/HOWTO.md | mdfilter |less -r ;;
+		curl -k $CLE_SRC/HOWTO.md | mdfilter |less -r;;
 	help)	## cle help [fnc|mod] -- show help for fuction or module
 		# double hash denotes help content
 		if [ -z "$1" ]; then
@@ -528,20 +525,20 @@ cle () {
 			# extract from given files
 			awk -F# "/[\t ]##|^##/ { print \$3 }" $*
 		else # search in modules
-			local HF=`echo $CLE_EXE | tr : '\n' |grep mod-.\*$1`
+			local HF=`echo $CLE_EXE | tr : '\n' |grep mod-$1`
 			[ -n "$HF" ] && cle help $HF || echo ...no help for you
-		fi ;;
+		fi;;
 	"")	_clebanner
 		sed -n 's/^#\*\(.*\)/\1/p' $CLE_RC # header
 		;;
-	*)	echo "'cle $CMD' not implemeted"
-		echo "check cle help"
+	*)	echo cle $CMD not implemeted
+		echo check cle help
 		return 1
 	esac
 }
 
 # remove disturbing stuff
-unset SUDO_COMMAND CLE_VERB CLE_DR
+unset SUDO_COMMAND CLE_VERB CLE_DT
 
 fi
 # and that's all the magic :-)
